   # Daily Weather Dataset

### Task

1.	Import dataset in notebook
2.	Clean data
3.	Make a label
4.	Train Test Split
5.	Apply Logistic Regression
6.	Apply Decision Tree
7.	Apply K neighbor
8.	Apply Linear SVM
9.	Apply RandomForest
10.	Record the accuracy

### Objective
- To predict whether humidity will be high(1) or low(0) in afternoon from data

#### Importing modules

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  

#### Import Dataset

In [3]:
data=pd.read_csv('daily_weather.csv')
data.head()

number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0       0        918.060000     74.822000              271.100000   
1       1        917.347688     71.403843              101.935179   
2       2        923.040000     60.638000               51.000000   
3       3        920.502751     70.138895              198.832133   
4       4        921.160000     44.294000              277.800000   

   avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0            2.080354              295.400000            2.863283   
1            2.443009              140.471548            3.533324   
2           17.067852               63.700000           22.100967   
3            4.337363              211.203341            5.190045   
4            1.856660              136.500000            2.863283   

   rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                    0.0                0.0              42.420000   
1                    0.0                0.0              24.328697   
2                    0.0               20.0               8.900000   
3                    0.0                0.0              12.189102   
4                    8.9            14730.0              92.410000   

   relative_humidity_3pm  
0              36.160000  
1              19.426597  
2              14.460000  
3              12.742547  
4              76.740000

#### Data Statistics

In [5]:
data.shape

(1095, 11)

In [4]:
data.describe()

number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
count  1095.000000       1092.000000   1090.000000             1091.000000   
mean    547.000000        918.882551     64.933001              142.235511   
std     316.243577          3.184161     11.175514               69.137859   
min       0.000000        907.990000     36.752000               15.500000   
25%     273.500000        916.550000     57.281000               65.972506   
50%     547.000000        918.921045     65.715479              166.000000   
75%     820.500000        921.160073     73.450974              191.000000   
max    1094.000000        929.320000     98.906000              343.400000   

       avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
count         1092.000000             1092.000000         1091.000000   
mean             5.508284              148.953518            7.019514   
std              4.552813               67.238013            5.598209   
min              0.693451               28.900000            1.185578   
25%              2.248768               76.553003            3.067477   
50%              3.871333              177.300000            4.943637   
75%              7.337163              201.233153            8.947760   
max             23.554978              312.200000           29.840780   

       rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
count            1089.000000        1092.000000            1095.000000   
mean                0.203079         294.108052              34.241402   
std                 1.593952        1598.078779              25.472067   
min                 0.000000           0.000000               6.090000   
25%                 0.000000           0.000000              15.092243   
50%                 0.000000           0.000000              23.179259   
75%                 0.000000           0.000000              45.400000   
max                24.020000       17704.000000              92.620000   

       relative_humidity_3pm  
count            1095.000000  
mean               35.344727  
std                22.524079  
min                 5.300000  
25%                17.395000  
50%                24.380000  
75%                52.060000  
max                92.250000

In [11]:
len(data)-data.count()

number                    0
air_pressure_9am          3
air_temp_9am              5
avg_wind_direction_9am    4
avg_wind_speed_9am        3
max_wind_direction_9am    3
max_wind_speed_9am        4
rain_accumulation_9am     6
rain_duration_9am         3
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

#### Removing entries with null values

In [12]:
data.dropna(inplace=True)
len(data)-data.count()

number                    0
air_pressure_9am          0
air_temp_9am              0
avg_wind_direction_9am    0
avg_wind_speed_9am        0
max_wind_direction_9am    0
max_wind_speed_9am        0
rain_accumulation_9am     0
rain_duration_9am         0
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

#### Creating label Y -  high_humidity
( If relative_humidity at 3pm is greater than or equal average value than set value of high_humidity to 1 otherwise zero )

In [13]:
data.shape

(1064, 11)

In [18]:
Avg_value=data['relative_humidity_3pm'].mean()
print(Avg_value)

35.14838093290537


In [24]:
data['high_humidity'] = data['relative_humidity_3pm']>=data['relative_humidity_3pm'].mean()*1
data['high_humidity']=data['high_humidity'].astype(int)
##data['high_humidity'].head()

0    1
1    0
2    0
3    0
4    1
Name: high_humidity, dtype: int32

In [27]:
## column names
data.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm', 'high_humidity'],
      dtype='object')

#### Separating Features and Label

In [26]:
features = [
            'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
            'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
            'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am', 
            ]

label = ['high_humidity']

X = data[features]
y = data[label]

### spliting Data into training and testing

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0)

### Logistic Regression

In [33]:
print(X_train.shape)
y_train=y_train.values.ravel()
print(y_train.shape)

(798, 9)
(798,)


In [28]:
from sklearn.linear_model import LogisticRegression

In [34]:
logistic=LogisticRegression(random_state=0)
logistic.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
logistic.predict(X_test)

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1])

In [38]:
## prediction our accuaracy
print('Accuracy = ' + str(logistic.score(X_test,y_test)))

Accuracy = 0.9135338345864662


In [58]:
## parameters of our logistic Regression model

print('parameters are:')
print('')
print('Bias or Theta 0 = '+ str(logistic.intercept_))
print('')
print('Weights of each feature is:')
print(dict(zip(features,logistic.coef_[0])))

parameters are:

Bias or Theta 0 = [0.02230556]

Weights of each feature is:
{'air_pressure_9am': -0.006054372848247713, 'air_temp_9am': -0.0026535088848650937, 'avg_wind_direction_9am': 0.0009832302862909006, 'avg_wind_speed_9am': 1.0435128625861225, 'max_wind_direction_9am': 0.00381094955776493, 'max_wind_speed_9am': -0.8951783174464408, 'rain_accumulation_9am': -0.06381247132215319, 'rain_duration_9am': -0.00014063171257495656, 'relative_humidity_9am': 0.176122168046152}


In [79]:
Bias =                   0.02230556   
air_pressure_9am =      -0.006054372848247713   
air_temp_9am =          -0.0026535088848650937   
avg_wind_direction_9am = 0.0009832302862909006   
avg_wind_speed_9am =     1.0435128625861225   
max_wind_direction_9am = 0.00381094955776493   
max_wind_speed_9am =    -0.8951783174464408   
rain_accumulation_9am = -0.06381247132215319   
rain_duration_9am =     -0.00014063171257495656   
relative_humidity_9am =  0.176122168046152  

#### Import features

avg_wind_speed_9am :   1.0435128625861225   
relative_humidity_9am: 0.176122168046152    
max_wind_speed_9am :  -0.8951783174464408  

### Decision Tree Regression

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
tree=DecisionTreeClassifier(random_state=0)
tree.fit(X_train,y_train)
tree.predict(X_test)

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1])

In [61]:
tree.score(X_test,y_test)

0.9097744360902256

In [62]:
tree.feature_importances_

array([0.07160488, 0.07586254, 0.04299009, 0.03006244, 0.03092388,
       0.0341665 , 0.01029917, 0.00163008, 0.70246043])

In [66]:
print(dict(zip(features,tree.feature_importances_)))

{'air_pressure_9am': 0.07160488313935606, 'air_temp_9am': 0.07586254229294367, 'avg_wind_direction_9am': 0.042990086044703384, 'avg_wind_speed_9am': 0.030062438386445182, 'max_wind_direction_9am': 0.03092387663944257, 'max_wind_speed_9am': 0.03416649885546163, 'rain_accumulation_9am': 0.01029916891999678, 'rain_duration_9am': 0.0016300793462719508, 'relative_humidity_9am': 0.7024604263753788}


In [77]:
air_pressure_9am = 0.07160488313935606    
air_temp_9am =  0.07586254229294367    
avg_wind_direction_9am =  0.042990086044703384    
avg_wind_speed_9am =  0.030062438386445182    
max_wind_direction_9am =  0.03092387663944257    
max_wind_speed_9am =  0.03416649885546163    
rain_accumulation_9am =  0.01029916891999678    
rain_duration_9am =  0.0016300793462719508    
relative_humidity_9am =  0.7024604263753788

In [ ]:
relative_humidity_9am =  0.7024604263753788

### Support Vector Machine

In [86]:
from sklearn.svm import LinearSVC

In [88]:
svc=LinearSVC()

In [89]:
svc.fit(X_train,y_train)
svc.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0])

In [90]:
svc.score(X_test,y_test)

0.8195488721804511

In [91]:
## parameters of our Linear SVC model:

print('parameters are:')
print('')
print('Bias or Theta 0 = '+ str(svc.intercept_))
print('')
print('Weights of each feature is:')
print(dict(zip(features,svc.coef_[0])))

parameters are:

Bias or Theta 0 = [0.00023784]

Weights of each feature is:
{'air_pressure_9am': -0.0025831492304386494, 'air_temp_9am': 0.0010290592145546066, 'avg_wind_direction_9am': -0.0015109332338347102, 'avg_wind_speed_9am': 0.014281072792308757, 'max_wind_direction_9am': 0.002141052367360921, 'max_wind_speed_9am': -0.012562181073418267, 'rain_accumulation_9am': 0.00031035807008492446, 'rain_duration_9am': -0.0005261065408390871, 'relative_humidity_9am': 0.054984609807397763}


In [92]:
Bias=                    0.00023784   
air_pressure_9am =       -0.0025831492304386494   
air_temp_9am =           0.0010290592145546066   
avg_wind_direction_9am = -0.0015109332338347102   
avg_wind_speed_9am =     0.014281072792308757   
max_wind_direction_9am = 0.002141052367360921   
max_wind_speed_9am =    -0.012562181073418267   
rain_accumulation_9am =  0.00031035807008492446   
rain_duration_9am =     -0.0005261065408390871   
relative_humidity_9am =  0.054984609807397763

### KNeighborsClassifier

In [94]:
from sklearn.neighbors import KNeighborsClassifier

In [95]:
K = range(1,20)
K_score = []
print('k          accuracy')
for k in K:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)
    score = knn.score(X_test,y_test)
    K_score.append(score)
    print(str(k) + '          ' + str(score))

k          accuracy
1          0.8721804511278195
2          0.8609022556390977
3          0.8796992481203008
4          0.8721804511278195
5          0.8909774436090225
6          0.8721804511278195
7          0.8721804511278195
8          0.868421052631579
9          0.8796992481203008
10          0.8721804511278195
11          0.8759398496240601
12          0.8609022556390977
13          0.8646616541353384
14          0.8533834586466166
15          0.8646616541353384
16          0.8571428571428571
17          0.8571428571428571
18          0.8609022556390977
19          0.8646616541353384


we get maximum accuracy at k=5  
5 ----->>   0.8909774436090225

### Random Forests

In [97]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\QCs\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [104]:
estimators = [10,20,30,40,50,60,70,80,90,100,120,140,160]
depth = [2,3,4]
print('estimators    depth          accuracy')
for i in estimators:
    for j in depth:
        forest = RandomForestClassifier(n_estimators=i, max_depth=j, random_state=0)
        forest.fit(X_train, y_train)
        score=forest.score(X_test,y_test)
        print(str(i)+ '             ' + str(j) + '          ' + str(score))

estimators    depth          accuracy
10             2          0.8984962406015038
10             3          0.9285714285714286
10             4          0.924812030075188
20             2          0.9172932330827067
20             3          0.9210526315789473
20             4          0.924812030075188
30             2          0.9060150375939849
30             3          0.9172932330827067
30             4          0.924812030075188
40             2          0.9097744360902256
40             3          0.9172932330827067
40             4          0.9210526315789473
50             2          0.9097744360902256
50             3          0.9210526315789473
50             4          0.9210526315789473
60             2          0.9172932330827067
60             3          0.9060150375939849
60             4          0.9210526315789473
70             2          0.9172932330827067
70             3          0.9135338345864662
70             4          0.924812030075188
80             2     

In [109]:
dict(zip(features,forest.feature_importances_))

{'air_pressure_9am': 0.12700420857293165,
 'air_temp_9am': 0.10203290933625835,
 'avg_wind_direction_9am': 0.041933537954216726,
 'avg_wind_speed_9am': 0.01984327671164985,
 'max_wind_direction_9am': 0.08662115094670865,
 'max_wind_speed_9am': 0.019262536112704974,
 'rain_accumulation_9am': 0.00562408320835605,
 'rain_duration_9am': 0.009178587444436058,
 'relative_humidity_9am': 0.5884997097127374}

#### important features

In [111]:
air_pressure_9am =      0.12700420857293165
air_temp_9am =          0.10203290933625835
relative_humidity_9am = 0.5884997097127374

## Summary
### Accuracy of different models

In [113]:
print('      Model                          Accuracy')
print('Logistic Regression =          0.9135338345864662')
print('Decision Tree Regression =     0.9097744360902256')
print('Support Vector Machine =       0.8195488721804511')
print('KNeighborsClassifier =         0.8909774436090225  (with k=5)')
print('Random Forests =               0.9285714285714286 (estimators=10, depth=3)')

      Model                          Accuracy
Logistic Regression =          0.9135338345864662
Decision Tree Regression =     0.9097744360902256
Support Vector Machine =       0.8195488721804511
KNeighborsClassifier =         0.8909774436090225  (with k=5)
Random Forests =               0.9285714285714286 (estimators=10, depth=3)


#### Conclusion:   
    Random Forest has so far given the best accuracy    